### ISSUE TITLE
Installation via conda

### ISSUE THREAD

**Issue by Rachine** [mmmaat/wordseg#3]
Hey,

J'essaie d'installer wordseg via conda, mais lors du build `python setup.py build` j'ai cette erreur
`compiling C++ dependencies for dpseg in build/dpseg
g++ -o /home/rriad/wordseg/build/dpseg/dpseg.o -c src/dpseg.cc -Wall -O3 -std=c++11 -I./include -DNDEBUG
src/dpseg.cc:33:47: fatal error: boost/detail/utf8_codecvt_facet.ipp: No such file or directory`

C'est lors d'un include ici: https://github.com/mmmaat/wordseg/blob/master/wordseg/algos/dpseg/src/dpseg.cc#L33
Comment on include le path pour ajouter les lib de l'environnement?

Merci !

**Comment by mmmaat** [comment]
Tu as bien créé ton virtualenv en installant boost ?

```
conda create --name wordseg python=3 \
      pytest pytest-runner sphinx sphinx_rtd_theme \
      boost joblib numpy pandas
```

Si ça ne marche toujours pas, sous linux essaie ``sudo apt-get install libboost-dev``

**Comment by mmmaat** [comment]
Another way should be to modify your environment variables (see https://conda.io/docs/building/shared-libraries.html#shared-libraries-in-linux-and-os-x), your conda installed boost must be in ~/.anaconda/envs/wordseg/{include/lib}

**I'll make this automatic in a newt commit**, thank's for reporting!

**Comment by mmmaat** [comment]
I tried it, didn't work with boost 1.61 from conda... 

So the installation procedure has been updated to use the system's boost package only.
